paths:
  /api/products:
    get:
      summary: List of products
      tags:
        - Products
      responses:
        200:
          description: Products were listed correctly.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la respuesta
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
        500:
          description: Internal Server Error.

  /api/products/{productId}:
    get:
      summary: Get an user by identifer
      tags:
        - Products
      parameters:
      - in: path
        name: productId
        required: true
        description: Identifier of the product to search
        schema:
          type: string
      responses:
        200:
          description: Product with valid identifier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Product not found
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  status: 
                    type: string
                    description: error
                    example: error
                  message:
                    type: string
                    description: product with productId not found
                    example: "Product with 655a45ff59dcc07a93eff698 not found"      
        500:
          description: Internal Server Error.


components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Product ID generated by data base
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product features and information
        price:
          type: float
          description: Product price
        thumbnail:
          type: string
          description: Product Image URL
        code:
          type: string
          description: A product unique code
        stock:
          type: int
          description: Number of available products
        category:
          type: string
          description: Department which product belongs
        owner:
          type: object
          properties:
            first_name:
              type: string
              description: Owner's first name
            last_name:
              type: string
              description: Owner's last name
            email:
              type: string
              description: Owner's email
      example:
        _id: 655a45ff59dcc07a93eff688
        title: Licuadora Oster
        description: Licuadora de alto rendimiento con cuchillas de acero inoxidable y jarra de vidrio resistente.
        price: 799.99
        thumbnail: https://m.media-amazon.com/images/I/51X0jzGB9NL._AC_UF894,1000_QL80_.jpg
        code: OST123
        stock: 16
        category: cocina
        owner:
          first_name: Jorge
          last_name: Infante
          email: jinfante2212@gmail.com
